### ISSUE TITLE
Add virtualization protection

### ISSUE THREAD

**Issue by nimix3** [HoLLy-HaCKeR/Confuser.Protections.HoLLy#14]
Hello HoLLy-HaCKer

Amazing works, You can also add an extra layer of protection (Virtualization Section) from KoiVM to this project. 
KoiVM is old but with some changes, It can be good and DeVirt proof

[https://github.com/Loksie/KoiVM-Virtualization](https://github.com/Loksie/KoiVM-Virtualization)

Thank you,

**Comment by holly-hacker** [comment]
KoiVM is already an existing plugin for ConfuserEx, it wouldn't feel right to "steal" it and add it to this project. However, I may make some kind of virtualization protection in the future (already experimented with it, should be doable).

**Comment by nimix3** [comment]
As I checked KoiVM is a dead project, because owner not support or sell it anymore,
I don't recommend anyone to hijack another work, just see this project is now OpenSource on Github and suggest you use it as an extra protection layer for your amazing protector. 
If you are interested to work on it as Pro and Commercial product or also work on virtualization on Java to create Android App Protector I am glad to work with you on it, I have some experience on Security and analyzing applications and securing communications.
Please tell me if you wish to work together.
Good Job,

**Comment by holly-hacker** [comment]
Gonna close this because KoiVM already exists and is (from what I heard) way better than anything I'd make. In the unlikely case I make my own virtualizer, I'd probably keep it private since the only thing it'd have going for it would be obscurity.
