### ISSUE TITLE
Provide compiled binaries

### ISSUE THREAD

**Issue by RoyIL** [HoLLy-HaCKeR/Confuser.Protections.HoLLy#6]
Hey there! I tried to setup your addon for ConfuserEX and the assembly looks like Confuser.Core?
However I want to try it and maybe contribute later, Could you help me with the setup?
Thanks (:

**Comment by holly-hacker** [comment]
Just build the project (output is Confuser.Protections.HoLLy.dll) and add it as a plugin in ConfuserEx.

**Comment by RoyIL** [comment]
Also, Can you please attach a link for compiled files download here?
I am using VS2015 (No support for C# 7.0)
I'll appreciate that, Thanks!

**Comment by holly-hacker** [comment]
No. You will have to update to VS17 eventually anyway, so you better do it now. If it really is that much trouble, just change the C#7.1 to C#6.x or earlier. 

I'm still developing this. Once there are more features and they fully work, I will consider making an actual release. Right now it's still pretty new.

**Comment by holly-hacker** [comment]
Compiled binaries can be found at [AppVeyor](https://ci.appveyor.com/project/HoLLy-HaCKeR/confuser-protections-holly/build/artifacts). 

Keep in mind that this still in development and at no point will I ever guarantee it works.
