### ISSUE TITLE
game develap ConfuserEX un

### ISSUE THREAD

**Issue by ahmedgamedev** [HoLLy-HaCKeR/Confuser.Protections.HoLLy#9]
ConfuserEX un
it is possable?

game.. YES.. ConfuserEX.. NO.. GAME ConfuserEx

sorry it is. game HoLLy.AntiWatermark HoLLy.FakeObfuscator HoLLy.MemoryProtection **REMOVE** game. how

**Comment by ahmedgamedev** [comment]
iam ahmed

**Comment by holly-hacker** [comment]
I have no clue what you mean.

**Comment by ahmedgamedev** [comment]
ConfuserEX Confuser.Protections.HoLLy **REMOVE** game dev

**Comment by holly-hacker** [comment]
Yeah you're going to need to learn some English and make proper sentences, or I won't be able to help you.

**Comment by ahmedgamedev** [comment]
*REMOVE* ConfuserEX Confuser.Protections.HoLLy 

game dev ahmed

**Comment by ahmedgamedev** [comment]
game dev

**Comment by holly-hacker** [comment]
Sorry, can't help you.

**Comment by ahmedgamedev** [comment]
game dev why
